# import numpy as a 
# list=[19,21,13,14,13,33,22,111,44,556,67,77]
# list.sort()
# print(list)  # inplace sorting
# a1=a.array(list)
# a2=a.sort(list)
# a3=a.sort(list)[:: -1]
# a4=a.argsort(list)
# print(a2)
# print(a3)
# print(a4)



import numpy as b
list1=b.array([[10,110,30],[40,50,60],[70,80,90]])
print(b.sort(list1,axis=0))
print(b.sort(list1,axis=1))


# x=b.sort(list1)[::-1]
# x=b.sort(list1)
# x=b.sort(list1,axis=0)
# # x=b.sort(list1)(list1,axis=1)
# print(b.sort(list))




squares = [x**2 for x in range(5)]
print(squares)



